cadastro/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.conf.urls import patterns

from . import views
from importa.views import loga, valida_usuario, sair

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^filiado/novo$', views.FiliadoCreate.as_view(), name='filiado-novo'),
	url(r'^filiado/altera/(?P<pk>[0-9]+)/$', views.FiliadoUpdate.as_view(), name='altera'),
	url(r'^filiado/deleta/(?P<pk>[0-9]+)/$', views.FiliadoDeleta.as_view(), name='deleta'),
	url(r'^filiado/pesquisa$', views.FiliadoList.as_view(), name='filiado-pesquisa'),
	#url(r'^cadastro/$', views.cadastro, name='cadastro'),
	#url(r'^contribuicoes/$', views.contribuicoes, name='contribuicoes'),

	url(r'^loga/$', loga, name='loga'),
	url(r'^valida-usuario/$', valida_usuario, name='valida-usuario'),
	url(r'^sair/$', sair, name='sair'),
]

cidades/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
	url(r'^estados/$', views.estados, name='estados'),
	url(r'^estado/(?P<id>[0-9]+)/$', views.estado, name='estado'),
	url(r'^cidades/(?P<id>[0-9]+)/$', views.cidades, name='cidades'),
	url(r'^cidade/(?P<id>[0-9]+)/$', views.cidade, name='cidade'),
]

sindicamara/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
	url(r'^importa/', include('importa.urls')),
	url(r'^cidades/', include('cidades.urls')),
    url(r'^cadastro/', include('cadastro.urls')),
    url(r'^admin/', admin.site.urls),
]

cadastro/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models
from django.db.models import Sum
from smart_selects.db_fields import ChainedForeignKey

SITUACAO_SINDICAL = (
    ('A', 'ATIVO'),
    ('I', 'INATIVO'),
)

ESTADO_CIVIL = (
    ('S', 'SOLTEIRO'),
    ('C', 'CASADO'),
    ('D', 'DIVORCIADO'),
    ('U', 'UNIÃO ESTÁVEL'),
    ('V', 'VIÚVO'),
)

@python_2_unicode_compatible
class Filiado(models.Model):
	matricula = models.CharField(max_length=4, unique=True)
	nome = models.CharField(max_length=200)
	situacao_funcional = models.ForeignKey('SituacaoFuncional')
	situacao_sindical = models.CharField(max_length=1, choices=SITUACAO_SINDICAL)
	data_filiacao = models.DateField(blank=True, null=True)
	email = models.EmailField(blank=True, null=True)
	data_nascimento = models.DateField(blank=True, null=True)
	cpf = models.CharField(max_length=14, blank=True, null=True)
	rg = models.CharField(max_length=11, blank=True, null=True)
	estado_civil = models.CharField(max_length=1, choices=ESTADO_CIVIL, blank=True, null=True)
	endereco = models.CharField(max_length=300, blank=True, null=True)
	bairro = models.CharField(max_length=200, blank=True, null=True)
	cep = models.CharField(max_length=8, blank=True, null=True)
	telefone = models.CharField(max_length=9, blank=True, null=True)
	setor = models.ForeignKey('Setor', blank=True, null=True)
	cargo = models.ForeignKey('Cargo', blank=True, null=True)
	cidade = models.IntegerField(blank=True, null=True)
	estado = models.IntegerField(blank=True, null=True)

	def __str__(self):
		return self.nome

	def matricula_formatada(self):
		return self.matricula.zfill(4)


@python_2_unicode_compatible
class SituacaoFuncional(models.Model):
	nome = models.CharField(max_length=200)

	def __str__(self):
		return self.nome


@python_2_unicode_compatible
class Setor(models.Model):
	nome = models.CharField(max_length=200)

	def __str__(self):
		return self.nome


@python_2_unicode_compatible
class Cargo(models.Model):
	nome = models.CharField(max_length=200)

	def __str__(self):
		return self.nome


@python_2_unicode_compatible
class Ramal(models.Model):
	ramal = models.CharField(max_length=4)
	filiado = models.ForeignKey('Filiado', on_delete=models.CASCADE)

	def __str__(self):
		return self.ramal		

cadastro/forms.py
# -*- coding: utf-8 -*-

from django.forms import ModelForm, CharField, DecimalField, DateField, BooleanField
from django.forms.models import inlineformset_factory
from django.forms import formsets, models
from django.forms.models import modelformset_factory
from django.core.exceptions import ValidationError
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Field, Div, Button, HTML, ButtonHolder
from crispy_forms.bootstrap import (PrependedText, PrependedAppendedText, FormActions, AppendedText)
from crispy_forms.bootstrap import StrictButton
from django.conf import settings
from decimal import Decimal
from django import forms

from datetime import datetime

from .models import SituacaoFuncional, SITUACAO_SINDICAL, ESTADO_CIVIL, Filiado, Cargo, Setor

class FiliadoPesquisa(forms.Form):

	matricula = forms.CharField(label='Matrícula', required=False)
	nome = forms.CharField(label='Nome', required=False)
	situacao_funcional = forms.ModelChoiceField(label='Situação Funcional', queryset=SituacaoFuncional.objects.all(), required=False)
	situacao_sindical = forms.ChoiceField(label='Situação Sindical', choices=SITUACAO_SINDICAL, required=False)

	def __init__(self, *args, **kwargs):
		super(FiliadoPesquisa, self).__init__(*args, **kwargs)

		self.helper = FormHelper()
		self.helper.form_tag = False
		self.helper.layout = Layout(
			Div(
				Div('matricula', css_class='col-md-2',),
				Div('nome', css_class='col-md-10',),
				css_class='col-md-12 row',
			),
			Div(
				Div('situacao_funcional', css_class='col-md-6',),
				Div('situacao_sindical', css_class='col-md-6',),
				css_class='col-md-12 row',
			),
			Div(
				Div(
					StrictButton('Pesquisar', css_class="btn-primary btn", id='btn_search', onclick='pesquisa()'),
					StrictButton('Imprimir', css_class="btn-default btn", id='btn_print', onclick='imprime()'),
					StrictButton('Incluir Filiado', css_class="btn-default btn", id='btn_new', onclick='novo()'),
					css_class='col-xs-12',
				),
				css_class='col-xs-12 row',
			),
		)


class FiliadoForm(ModelForm):
	matricula = forms.CharField(label='Matrícula')
	nome = forms.CharField(label='Nome')
	situacao_funcional = forms.ModelChoiceField(label='Situação Funcional', queryset=SituacaoFuncional.objects.all())
	situacao_sindical = forms.ChoiceField(label='Situação Sindical', choices=SITUACAO_SINDICAL)
	data_filiacao = forms.DateField(label='Data de Filiação', required=False)
	email = forms.EmailField(label='email', required=False)
	data_nascimento = forms.DateField(label='Data de Nascimento', required=False)
	cpf = forms.CharField(label='CPF', required=False)
	rg = forms.CharField(label='RG', required=False)
	estado_civil = forms.ChoiceField(label='Estado Civil', choices=ESTADO_CIVIL, required=False)
	endereco = forms.CharField(label='Endereço', required=False)
	bairro = forms.CharField(label='Bairro', required=False)
	cep = forms.CharField(label="CEP", required=False)
	telefone = forms.CharField(label='Telefone', required=False)
	setor = forms.ModelChoiceField(label='Setor', queryset=Setor.objects.all().order_by('nome'))
	cargo = forms.ModelChoiceField(label='Cargo', queryset=Cargo.objects.all().order_by('nome'))
	cidade = forms.IntegerField(required=False)
	estado = forms.IntegerField(required=False)

	class Meta:
		model = Filiado
		exclude = ['']

	def __init__(self, *args, **kwargs):
		super(FiliadoForm, self).__init__(*args, **kwargs)

		self.helper = FormHelper()
		self.helper.form_tag = False
		self.helper.layout = Layout(
			Div(
				Div('matricula', css_class='col-md-2',),
				Div('nome', css_class='col-md-10',),
				css_class='col-md-12 row',
			),
			Div(
				Div('setor', css_class='col-md-6',),
				Div('cargo', css_class='col-md-6',),
				css_class='col-md-12 row',
			),
			Div(
				Div('situacao_funcional', css_class='col-md-6',),
				Div('situacao_sindical', css_class='col-md-6',),
				css_class='col-md-12 row',
			),
			Div(
				Div(AppendedText('data_filiacao', '<span class="glyphicon glyphicon-calendar"></span>'), css_class='col-md-4',),
				Div('estado_civil', css_class='col-md-4',),
				Div('email', css_class='col-md-4',),
				css_class='col-md-12 row',
			),
			Div(
				Div('cpf', css_class='col-md-6',),
				Div('rg', css_class='col-md-6',),
				css_class='col-md-12 row',
			),
			Div(
				Div('endereco', css_class='col-md-12',),
				css_class='col-md-12 row',
			),
			Div(
				Div('bairro', css_class='col-md-4',),
				Div('cep', css_class='col-md-4',),
				Div('telefone', css_class='col-md-4',),
				css_class='col-md-12 row',
			),
		)


class UploadContribuicoesForm(forms.Form):
	data = forms.DateField()
	arquivo_cmc = forms.FileField()
	arquivo_ipmc = forms.FileField()

	def __init__(self, *args, **kwargs):
		super(UploadContribuicoesForm, self).__init__(*args, **kwargs)

		self.helper = FormHelper()
		self.helper.form_method = 'post'
		self.helper.form_tag = False
		self.helper.layout = Layout(
			Div(
				Div(AppendedText('data', '<span class="glyphicon glyphicon-calendar"></span>'), css_class='col-md-6',),
				css_class='col-md-12 row',
			),
			Div(
				Div('arquivo_cmc', css_class='col-md-6',),
				Div('arquivo_ipmc', css_class='col-md-6',),
				css_class='col-md-12 row',
			),
			Div(
				Div(FormActions(Submit('save', 'Importar')), css_class='col-md-6',),
				css_class='col-md-12 row',
			),
		)

	def clean_data(self):
		data = self.cleaned_data['data']
		array_data = datetime.strftime(data, "%d/%m/%Y").split("/")
		str_data = '01/' + array_data[1] + '/' + array_data[2]
		data_f = datetime.strptime(str_data, "%d/%m/%Y")

		if Contribuicao.objects.filter(data=data_f).exists():
			raise forms.ValidationError("Já foi importado a contribuição de %s/%s" % (array_data[1], array_data[2]))
		return data


class UploadCadastroForm(forms.Form):
	arquivo_ativos = forms.FileField()
	arquivo_inativos = forms.FileField()	

	def __init__(self, *args, **kwargs):
		super(UploadCadastroForm, self).__init__(*args, **kwargs)

		self.helper = FormHelper()
		self.helper.form_method = 'post'
		self.helper.form_tag = False
		self.helper.layout = Layout(
			Div(
				Div('arquivo_ativos', css_class='col-md-6 file',),
				Div('arquivo_inativos', css_class='col-md-6',),
				css_class='col-md-12 row',
			),
			Div(
				Div(FormActions(Submit('save', 'Importar')), css_class='col-md-6',),
				css_class='col-md-12 row',
			),
		)

cadastro/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render_to_response
from django.shortcuts import render
from django.views.generic.edit import CreateView
from django.views.generic.edit import UpdateView
from django.views.generic.edit import DeleteView
from django.views.generic.list import ListView
from django.views.generic.edit import FormView
from django.contrib.auth.decorators import login_required
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from .forms import UploadCadastroForm, UploadContribuicoesForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.shortcuts import render
from django.shortcuts import redirect
from django.utils.html import format_html
from django.contrib.auth.decorators import login_required
from django.utils.dateparse import parse_date
from django import forms
from django.db import connection, transaction
from django.contrib.messages.views import SuccessMessageMixin

from .forms import FiliadoPesquisa, FiliadoForm
from sindicamara.classes import seguranca
from .models import Filiado


@login_required(login_url='/cadastro/loga/')
def index(request):
	return render_to_response('index.html', context_instance=RequestContext(request))	


class FiliadoList(seguranca.SindicamaraLoginRequired, FormView):
	template_name = "cadastro/search.html"
	form_class = FiliadoPesquisa
	success_url = '/cadastro/filiado/pesquisa'

	def get(self, request, *args, **kwargs):
		context = self.get_context_data(**kwargs)
		context['form'] = FiliadoPesquisa(request.GET)
		#monta a query baseada nos argumentos do request e coloca o resultado no contexto
		matricula = request.GET.get('matricula', None)
		nome = request.GET.get('nome', None)
		situacao_funcional = request.GET.get('situacao_funcional', None)
		situacao_sindical = request.GET.get('situacao_sindical', 'A')
		filiados = Filiado.objects.all()

		if matricula is not None and matricula != '':
			filiados = Filiado.objects.filter(matricula=matricula)
		if nome is not None and nome != '':
			filiados = filiados.filter(nome__icontains=nome)
		if situacao_sindical is not None and situacao_sindical != '':
			filiados = filiados.filter(situacao_sindical=situacao_sindical)
		if situacao_funcional is not None and situacao_funcional != '':
			filiados = filiados.filter(situacao_funcional=situacao_funcional)
		context['filiados'] = filiados
		return self.render_to_response(context)


class FiliadoCreate(seguranca.SindicamaraLoginRequired, SuccessMessageMixin, CreateView):
	template_name = "cadastro/new.html"
	form_class = FiliadoForm
	model = Filiado
	success_url = '/cadastro/filiado/pesquisa'
	success_message = "Filiado criado com sucesso"


class FiliadoUpdate(seguranca.SindicamaraLoginRequired, SuccessMessageMixin, UpdateView):
	template_name = "cadastro/update.html"
	form_class = FiliadoForm	
	model = Filiado
	success_url = '/cadastro/filiado/pesquisa'
	success_message = "Filiado atualizado com sucesso"


class FiliadoDeleta(seguranca.SindicamaraLoginRequired, SuccessMessageMixin, DeleteView):
	model = Filiado
	template_name = "cadastro/deleta.html"
	success_url = '/cadastro/filiado/pesquisa'
	success_message = "Filiado excluído com sucesso"	

cadastro/templates/cadastro/deleta.html
{% extends "base.html" %}

{% block title %}Exclusão de Filiado{% endblock %}

{% block content %}

<form action="" method="post" id="formulario">
	{% csrf_token %}
	<h3>Tem certeza que deseja excluir o filiado : <span class="label label-danger">{{ object.matricula }} - {{ object.nome }}</span></h3>
	<button type="button" class="btn btn-secondary" onclick="javascript:nao();">Não</button>
	<button type="button" class="btn btn-danger" onclick="javascript:sim();">Sim</button>
</form>

{% endblock %}

{% block extra_javascript %}

	<script>
		function nao() {
			$(location).attr('href','/cadastro/filiado/pesquisa');
		}

		function sim() {
			$('#formulario').submit();
		}
	</script>

{% endblock %}

cadastro/templates/cadastro/new.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Inclusão de Filiado{% endblock %}

{% block content %}

<form action="" method="post" id="formulario">
	{% crispy form %}

	<div class="col-md-12 row">
		<div class="col-md-6"> 
			<div id="div_id_estado" class="form-group"> 
				<label for="id_estado" class="control-label requiredField">Estado</label>
				<div class="controls "> 
					<select class="select form-control" id="id_estado" name="estado">
						<option value="">------------------------------</option>
					</select> 
				</div> 
			</div>
		</div>
		<div class="col-md-6"> 
			<div id="div_id_cidade" class="form-group"> 
				<label for="id_cidade" class="control-label requiredField">Cidade</label>
				<div class="controls "> 
					<select class="select form-control" id="id_cidade" name="cidade">
						<option value="">------------------------------</option>
					</select> 
				</div> 
			</div>
		</div>
	</div>

	<div class="col-md-12 row"> 
		<div class="col-md-6"> 
			<div class="form-group"> 
				<div class="controls "> <input type="submit" name="save" value="Salvar" class="btn btn-primary" id="submit-id-save"/> </div>
			</div>

		</div>
	</div>

</form>

{% endblock %}

{% block extra_javascript %}

<script>
	$(document).ready(function () {
		$('.dateinput').datepicker({
			format: "dd/mm/yyyy",
			language: "pt-BR",
			todayHighlight: true,
			clearBtn: true,
			autoclose: true,
			orientation: "bottom left",
		});

		$('.dateinput').inputmask({
      		mask: '99/99/9999'
    	})

    	$('#id_cep').inputmask({
      		mask: '99.999-999'
    	})

    	$('#id_cpf').inputmask({
      		mask: '999.999.999-99'
    	})

    	$('#id_rg').inputmask({
      		mask: '9.999.999-9'
    	})

    	$('#id_telefone').inputmask({
      		mask: '9999-9999'
    	})

    	$('#formulario').submit(function() {
    		$('#id_cep').val($('#id_cep').val().replace('.', '').replace('-',''));
    		$('#id_cpf').val($('#id_cpf').val().replace('.', '').replace('-',''));
    		$('#id_rg').val($('#id_rg').val().replace('.', '').replace('-',''));
    		$('#id_telefone').val($('#id_telefone').val().replace('.', '').replace('-',''));
    	})

    	carregaEstados();

    	$('#id_estado').on('change', function() {
    		carregaCidades();
    	})
	});

	function carregaEstados() {
		request_url = '/cidades/estados/';

		$.ajax({
      		url: request_url,
      		type: 'GET',
      		accepts: 'application/json',
      		dataType: 'json',
      		success: function(result){
      			var toAppend = '';
      			$.each(result, function(index, element) {
      				if (element.ID == {{form.estado.value}})
      					toAppend += '<option selected="selected" value="' + element.ID + '">' + element.Nome + '</option>';
      				else
      					toAppend += '<option value="' + element.ID + '">' + element.Nome + '</option>';
      			});
      			$('#id_estado').append(toAppend);
      			carregaCidades();
      		},
      		error: function(xhr, status, error) {
        		alert('Erro ao carregar Estados');
            	alert(xhr);
            	alert(status);
            	alert(error);
      		}
    	})
    }

    function carregaCidades() {
    	$('#id_cidade').children().remove().end().append('<option selected value="">------------------------------</option>') ;

    	if ($('#id_estado option:selected').val() != '') {
    		request_url = '/cidades/cidades/' + $('#id_estado option:selected').val();
			$.ajax({
	      		url: request_url,
      			type: 'GET',
      			accepts: 'application/json',
      			dataType: 'json',
      			success: function(result){
	      			var toAppend = '';
      				$.each(result, function(index, element) {
	      				if (element.ID == {{form.cidade.value}})
      						toAppend += '<option selected="selected" value="' + element.ID + '">' + element.Nome + '</option>';
      					else
	      					toAppend += '<option value="' + element.ID + '">' + element.Nome + '</option>';
      				});
      				$('#id_cidade').append(toAppend);
      			},
      			error: function(xhr, status, error) {
	        		alert('Erro ao carregar Cidades');
            		alert(xhr);
            		alert(status);
            		alert(error);
      			}
    		})	
    	}
    }

</script>

{% endblock %}

cadastro/templates/cadastro/search.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Pesquisa de Filiado{% endblock %}

{% block content %}

<form action="" method="get" id="formulario">
	{% crispy form %}
</form>

<div class="col-md-12">
<div class="table-responsive">
<table id="tabela" class="table table-striped table-bordered" cellspacing="0" width="100%">
	<thead>
		<tr>
			<th>Matrícula</th>
			<th>Nome</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		{% for item in filiados %}
			<tr>
				<td><a href="altera/{{ item.id }}">{{ item.matricula_formatada }}</a></td>
				<td><a href="altera/{{ item.id }}">{{ item.nome }}</a></td>
				<td class="text-center"><a href="deleta/{{ item.id }}"><span class="glyphicon glyphicon-trash text-danger"></span></a></td>
			</tr>
		{% endfor %}
	</tbody>
</table>
</div></div>

{% endblock %}

{% block extra_javascript %}

<script>
	$(document).ready(function() {
    	$('#tabela').DataTable({
    		"bFilter": false,
    		"bLengthChange": false
    	});

    	$('input, select').keypress(function(event) {
    		if(event.keyCode === 13){
				$('#formulario').submit();
			}
		});

	} );

	function imprime() {
		alert('Não implementado');
	}

	function pesquisa() {
		$('#formulario').submit();
	}

	function novo() {
		$(location).attr('href','/cadastro/filiado/novo');
	}

</script>

{% endblock %}

cadastro/templates/cadastro/update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Alteração de Filiado{% endblock %}

{% block content %}

<form action="" method="post" id="formulario">
	{% crispy form %}

	<div class="col-md-12 row">
		<div class="col-md-6"> 
			<div id="div_id_estado" class="form-group"> 
				<label for="id_estado" class="control-label requiredField">Estado</label>
				<div class="controls "> 
					<select class="select form-control" id="id_estado" name="estado">
						<option value="">------------------------------</option>
					</select> 
				</div> 
			</div>
		</div>
		<div class="col-md-6"> 
			<div id="div_id_cidade" class="form-group"> 
				<label for="id_cidade" class="control-label requiredField">Cidade</label>
				<div class="controls "> 
					<select class="select form-control" id="id_cidade" name="cidade">
						<option value="">------------------------------</option>
					</select> 
				</div> 
			</div>
		</div>
	</div>

	<div class="col-md-12 row"> 
		<div class="col-md-6"> 
			<div class="form-group"> 
				<div class="controls "> <input type="submit" name="save" value="Salvar" class="btn btn-primary" id="submit-id-save"/> </div>
			</div>

		</div>
	</div>

</form>

{% endblock %}

{% block extra_javascript %}

<script>
	$(document).ready(function () {
		$('.dateinput').datepicker({
			format: "dd/mm/yyyy",
			language: "pt-BR",
			todayHighlight: true,
			clearBtn: true,
			autoclose: true,
			orientation: "bottom left",
		});

		$('.dateinput').inputmask({
      		mask: '99/99/9999'
    	})

    	$('#id_cep').inputmask({
      		mask: '99.999-999'
    	})

    	$('#id_cpf').inputmask({
      		mask: '999.999.999-99'
    	})

    	$('#id_rg').inputmask({
      		mask: '9.999.999-9'
    	})

    	$('#id_telefone').inputmask({
      		mask: '9999-9999'
    	})

    	$('#formulario').submit(function() {
    		$('#id_cep').val($('#id_cep').val().replace('.', '').replace('-',''));
    		$('#id_cpf').val($('#id_cpf').val().replace('.', '').replace('-',''));
    		$('#id_rg').val($('#id_rg').val().replace('.', '').replace('-',''));
    		$('#id_telefone').val($('#id_telefone').val().replace('.', '').replace('-',''));
    	})

    	carregaEstados();

    	$('#id_estado').on('change', function() {
    		carregaCidades();
    	})
	});

	function carregaEstados() {
		request_url = '/cidades/estados/';

		$.ajax({
      		url: request_url,
      		type: 'GET',
      		accepts: 'application/json',
      		dataType: 'json',
      		success: function(result){
      			var toAppend = '';
      			$.each(result, function(index, element) {
      				if (element.ID == {{form.estado.value}})
      					toAppend += '<option selected="selected" value="' + element.ID + '">' + element.Nome + '</option>';
      				else
      					toAppend += '<option value="' + element.ID + '">' + element.Nome + '</option>';
      			});
      			$('#id_estado').append(toAppend);
      			carregaCidades();
      		},
      		error: function(xhr, status, error) {
        		alert('Erro ao carregar Estados');
            	alert(xhr);
            	alert(status);
            	alert(error);
      		}
    	})
    }

    function carregaCidades() {
    	$('#id_cidade').children().remove().end().append('<option selected value="">------------------------------</option>') ;

    	if ($('#id_estado option:selected').val() != '') {
    		request_url = '/cidades/cidades/' + $('#id_estado option:selected').val();
			$.ajax({
	      		url: request_url,
      			type: 'GET',
      			accepts: 'application/json',
      			dataType: 'json',
      			success: function(result){
	      			var toAppend = '';
      				$.each(result, function(index, element) {
	      				if (element.ID == {{form.cidade.value}})
      						toAppend += '<option selected="selected" value="' + element.ID + '">' + element.Nome + '</option>';
      					else
	      					toAppend += '<option value="' + element.ID + '">' + element.Nome + '</option>';
      				});
      				$('#id_cidade').append(toAppend);
      			},
      			error: function(xhr, status, error) {
	        		alert('Erro ao carregar Cidades');
            		alert(xhr);
            		alert(status);
            		alert(error);
      			}
    		})	
    	}
    }

</script>

{% endblock %}